 - name: Add static services present on roles/services/var
   uri:
     url: http://localhost:9090/service
     method: POST
     body_format: json
     body: '{"name":"{{item.name_svc}}","ip":"{{item.ip_svc}}","port":"{{item.port_svc}}"}'  
     status_code: 200
   register: add_services
   with_items: "{{name_services}}"
