 

 - name: del service debug
   debug:
     msg: "{{name_services}}"
 


 - name: Delete services
   uri:
     url: "{{API_ADDR}}/service/{{name_services}}"
     method: DELETE
     
     status_code: 200
     headers:
       Content-Type: "application/json"
   register: register_delete_services
   
 - name: debug
   debug:
    msg: "{{register_delete_services}}"

