 - name: Delete services
   uri:
     url: "{{API_ADDR}}/service/{{item.name_svc}}"
     method: DELETE
     body_format: json
     #body: '{"name":"{{item.name_svc}}","ip":"{{item.ip_svc}}","port":"{{item.port_svc}}"}'  
   #  status_code: 200
   register: delete_services
   with_items: "{{name_services}}"
