---
- hosts: localhost
  
  pre_tasks:
  - include_vars: global_vars.yml
  - name: Query API to check if theres any LB present
    uri:
      url: "{{API_ADDR}}/lb"
    register: lb_json
  - set_fact:
      new_infra: true 
#    when: lb_json.json | length == 0 #UNCOMMENT




  tasks:
    - name: Build all compoments(LB,services and monitors)
      block:
      - include_role:
          name: loadbalancer
          tasks_from: add_lb
      
      - include_role:
          name: service
          tasks_from: add_service

      - include_role:
          name: monitor
          tasks_from: add_monitor
      - include_role:
          name: bind
          tasks_from: bind_svc_to_mon
      - include_role:
          name: bind
          tasks_from: bind_svc_to_lb
   #   - include_role:
   #       name: service
   #       tasks_from: del_service
      when: new_infra is defined  




