---
- hosts: localhost

  
  pre_tasks:

  - name: Query API to check if theres any LB present
    uri:
      url: "http://localhost:9090/lb"
    register: lb_json

  - set_fact:
      new_infra: true 
#    when: lb_json.json | length == 0 #UNCOMMENT




  tasks:
    - name: Build all compoments(LB,services and monitors)
      block:
      - include_role:
          name: loadbalancer
          tasks_from: add_lb
        #when: new_infra is defined
      - include_role:
          name: service
          tasks_from: add_service
      when: new_infra is defined  
  #roles:
  # - {role: loadbalancer, tags: add_lb, when: new_infra == true} 




