---
- hosts: localhost
    



  pre_tasks:
  - include_vars: global_vars.yml
  - copy: content="{{ new_ips }}" dest=/home/toca/ansible_lb_automation/ansible/ips.txt


  tasks:
    
    - name: get all components present on the LB 
      block:
      - include_role:
          name: service
          tasks_from: get_services
      - set_fact: 
          json_services: "{{register_get_services.json}}"



      - include_role:
          name: loadbalancer
          tasks_from: get_lbs

 
      - name: Add Temporary LoadBalancer
        uri:
         url: "{{API_ADDR}}/lb"
         method: POST
         body_format: json
         body: '{"name":"{{name_temp_lb}}","vip":"{{vip_temp_lb}}","port":"{{port_temp_lb}}","dns":{"ttl":"{{ttl_temp_lb}}","cname":"{{cname_temp_lb}}"}}'
         status_code: 200
         headers:
           Content-Type: "application/json"
        register: register_add_temp_lb


 #     - set_fact: 
 #         json_services_1: "{{ json_services | combine(new_item, recursive=true) }}"
 #       vars:
 #         new_item: "{ '{{ item.key }}': { 'ip': '197.1.1' } }"          
 #       with_dict: 
 #         - "{{ json_services }}"

 

     # - set_fact: 
    #      json_services_1: "{{ json_services | combine( { item: some_value } ) }}"
    #    vars:
    #      some_value: 12345
    #    with_dict:
    #      - "{awesomeapp_1: {'name': 'batatas'}}"
          
        

     # - name: BEFORE UPDATE IP
      #  debug:
      #    msg: "{{item}}"
     #   with_dict: "{{json_services_1}}"


    #  - name: TRY TO UPDATE IP
    #    debug:
          #msg: "{{item.value.ip}}"
      #  with_dict: "{{register_get_services.json}}"#

      - set_fact: name_lb_prod="{{item.key}}"
        with_dict:  "{{register_get_lbs.json}}"


       
    - include: core_play.yml
      with_dict:
        - "{{register_get_services.json}}"
      vars:
         - ip_file: "{{lookup('file', '/home/toca/ansible_lb_automation/ansible/ips.txt') }}"




  post_tasks:     
    - name: Delete Temporary LoadBalancer
      uri:
        url: "{{API_ADDR}}/lb/{{name_temp_lb}}"
        method: DELETE
     
        status_code: 200
        headers:
          Content-Type: "application/json"
      register: register_delete_temp_lb
    - name: All services updated
      debug:
       msg: "IPs from all services updated."
   
 
    
        
      




    
      

  





