---
- hosts: localhost
    
  pre_tasks:
  - include_vars: global_vars.yml
  - name:
    debug:
      msg: "{{playbook_dir + 'ips.txt'}}"

  - fail:
      msg: "Usage format: ansible-playbook update_ip.yml -k -e new_ips=<ip1,ip2,..>"
    when: new_ips is not defined  
  - copy: content="{{ new_ips }}" dest="{{ playbook_dir + '/files/ips.txt'}}" 


  tasks:
    
    - name: get all components present on LoadBalancer.
      block:
      - include_role:
          name: service
          tasks_from: get_services
      - set_fact: 
          json_services: "{{register_get_services.json}}"



      - include_role:
          name: loadbalancer
          tasks_from: get_lbs

 
      - name: Add temporary LoadBalancer.
        uri:
         url: "{{API_ADDR}}/lb"
         method: POST
         body_format: json
         body: '{"name":"{{name_temp_lb}}","vip":"{{vip_temp_lb}}","port":"{{port_temp_lb}}","dns":{"ttl":"{{ttl_temp_lb}}","cname":"{{cname_temp_lb}}"}}'
         status_code: 200
         headers:
           Content-Type: "application/json"
        register: register_add_temp_lb



      - set_fact: name_lb_prod="{{item.key}}"
        with_dict:  "{{register_get_lbs.json}}"





    - include: core_play.yml
      with_dict:
        - "{{register_get_services.json}}"
      vars:
         - ip_file: "{{lookup('file', 'ips.txt') }}"





  post_tasks:     
    - name: Delete temporary LoadBalancer.
      uri:
        url: "{{API_ADDR}}/lb/{{name_temp_lb}}"
        method: DELETE
     
        status_code: 200
        headers:
          Content-Type: "application/json"
      register: register_delete_temp_lb
    - name: All services updated
      debug:
       msg: "IPs from all services updated."
   
 
    
        
      




    
      

  





